# GraphRAG System Configuration
# Centralized configuration to replace hardcoded values

# Entity Processing Configuration
entity_processing:
  confidence_threshold: 0.7        # Minimum confidence for entity extraction
  chunk_overlap_size: 50           # Character overlap between text chunks
  embedding_batch_size: 100        # Batch size for embedding processing
  max_entities_per_chunk: 20       # Maximum entities to extract per chunk

# Text Processing Configuration  
text_processing:
  chunk_size: 512                  # Size of text chunks for processing
  semantic_similarity_threshold: 0.85  # Threshold for semantic similarity matching
  max_chunks_per_document: 100     # Maximum chunks per document

# Graph Construction Configuration
graph_construction:
  pagerank_iterations: 100         # Maximum PageRank iterations
  pagerank_damping_factor: 0.85    # PageRank damping factor
  pagerank_tolerance: 0.000001     # Convergence tolerance for PageRank
  pagerank_min_score: 0.0001       # Minimum PageRank score to consider
  max_relationships_per_entity: 50 # Maximum relationships per entity
  graph_pruning_threshold: 0.1     # Threshold for graph pruning

# API Configuration
api:
  retry_attempts: 3                # Number of retry attempts for API calls
  timeout_seconds: 30              # Timeout for API requests
  batch_processing_size: 10        # Batch size for API processing
  openai_model: "text-embedding-3-small"  # OpenAI embedding model
  gemini_model: "gemini-2.0-flash-exp"    # Google Gemini model

# Neo4j Database Configuration
neo4j:
  uri: "bolt://localhost:7687"     # Neo4j connection URI
  user: "neo4j"                    # Neo4j username
  password: "password"             # Neo4j password
  max_connection_pool_size: 50     # Maximum connection pool size
  connection_acquisition_timeout: 30.0  # Connection timeout in seconds
  keep_alive: true                 # Keep connections alive

# System Configuration
environment: "development"         # Environment: development, staging, production
debug: false                      # Enable debug logging
log_level: "INFO"                 # Logging level: DEBUG, INFO, WARNING, ERROR